import { Footer } from "./components/Footer";
import { Header } from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zdorova voda Odessa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <main className="container">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
